name: smart_attendance
description: A new Flutter project.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  animated_splash: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^0.12.5+1
  image_picker: ^0.6.0+9                                             # new
 # google_sign_in: ^4.0.2                                           # new
  #firebase_analytics: ^3.0.2                                      # new
  firebase_auth: ^0.11.1+6                                            # new
  firebase_database: ^3.0.2                                       # new
  firebase_storage: ^3.0.1
  firebase_core: ^0.4.0+5                                     # new
  path_provider: ^2.0.2
  barcode_scan: ^1.0.0
  qr_flutter: ^2.1.0+55
  sqflite: ^1.1.5
  xxtea: ^2.0.2
  back_button_interceptor: ^4.0.6
  splashscreen: ^1.3.5
  flutter_splash: ^1.0.1
  animated_splash: ^1.0.0
  downloads_path_provider: ^0.1.0
  csv: ^5.0.0
  flutter_launcher_icons: ^0.8.0
  geolocator: ^7.1.0
  local_auth: ^1.1.6
  screenshot: ^1.2.1
  image_gallery_saver: ^1.6.9
  permission_handler: ^8.1.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/res/
    - assets/login-screen-background.png
    - assets/signup-screen-background.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/applogo.jpg"